version: '3.9'

services:
  app:
    build: .
    entrypoint: ./entrypoint-prod.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"